### ISSUE TITLE
lost crawl and scrape bug?

### ISSUE THREAD

**Issue by wymen2018** [my8100/scrapydweb#1]
why i lost crawl and scrape，lost items count
![hp1 a nt3ygh24 7bdois](https://user-images.githubusercontent.com/38031556/46584991-3d2f8200-ca9d-11e8-84e0-7631d1e886e1.png)

**Comment by wymen2018** [comment]
另外可以有中文版界面吗，也没有定时器功能，可以和spiderkeeper一起使用吗？

**Comment by my8100** [comment]
> why i lost crawl and scrape，lost items count
> ![hp1 a nt3ygh24 7bdois](https://user-images.githubusercontent.com/38031556/46584991-3d2f8200-ca9d-11e8-84e0-7631d1e886e1.png)

It's no need to show crawling progress with chart when crawled_pages is 0.

**Comment by my8100** [comment]
> 另外可以有中文版界面吗，也没有定时器功能，可以和spiderkeeper一起使用吗？

"dual languages switch" and "run spider periodly" may be added in future updates.
ScrapydWeb has nothing to do with spiderkeeper, but you have to **set different ports** for them.
PS: It's better to use English on GitHub.
