### ISSUE TITLE
Timer task results in too many pending spider jobs

### ISSUE THREAD

**Issue by crud-boy** [my8100/scrapydweb#101]
Can you add a timeout to delete pending tasks and running tasks? Otherwise, when there are too many tasks, it will cause stuck

**Comment by my8100** [comment]
Don’t mix up the concept of “spider job” and “timer task”. 
1. Manually set up the [max_proc](https://scrapyd.readthedocs.io/en/stable/config.html#max-proc) option to enable more concurrent Scrapy process. 
2. Decrease the frequency of your timer task if necessary.
