### ISSUE TITLE
How to make working with Portia Project?

### ISSUE THREAD

**Issue by xianx** [my8100/scrapydweb#105]
I am trying to deploy a Portia project exported from Portia https://techtun.es/aSY520.

But after uploading the Portia Project it cannot be deployed. No spider is listed. Please see the video https://techtun.es/7yHGgI.

Here is the Portia project file https://techtun.es/aJxIMg

How to make working with Portia Project?

Note that Exporting as 'Scrapy Project' from Portia https://techtun.es/AO8jYz works fine with scrapydweb. But I need to make Protia Project to work with scrapydweb.

Thanks in advanced.

**Comment by my8100** [comment]
It's not an issue of ScrapydWeb.
You have to make sure that "Download as Portia" works for Scrapyd first.
