### ISSUE TITLE
Can crawlers be automatically assigned to different node  based on the load of the each node when timer tasks start?

### ISSUE THREAD

**Issue by bao197129** [my8100/scrapydweb#106]
It seem to be that  the task is simultaneously  started on all nodes which I select，Can‘t  crawlers be automatically assigned to one different node  when I select multiple nodes？

**Comment by my8100** [comment]
No, there's no load balancing when executing a timer task.
You may set up the [**max_proc**](https://scrapyd.readthedocs.io/en/latest/config.html#max-proc) option on Scrapyd to avoid pending spider jobs.
