### ISSUE TITLE
[BUG]'pip install logparser' on host '192.168.1.111:6800' and run command 'logparser' to show crawled_pages and scraped_items.

### ISSUE THREAD

**Issue by Chenhonli** [my8100/scrapydweb#108]
**Describe the bug**
if I want to parser 192.168.1.111：6800 host logs . what to do? 
I already  install logparser on host  '192.158.1.111:6800'

**Environment (please complete the following information):**
 - OS: [ Win server 2008]
 - Python: [ 3.7.3]
 - ScrapydWeb: [ 1.0.0]

**Comment by Chenhonli** [comment]
it' ok! thanks!
set scrapyd.conf on 192.168.1.111:6800 , find log_dir then modify logparser's settings SCRAPYD_LOGS_DIR.

**Comment by my8100** [comment]
BTW, `pip install —update scrapydweb`
