### ISSUE TITLE
[BUG]addversion.json timeout

### ISSUE THREAD

**Issue by kjxy** [my8100/scrapydweb#111]
**Describe the bug**
`{ "auth": null, "message": "('Connection aborted.', timeout('timed out',))", "status": "error", "status_code": -1, "url": "http://192.168.1.211:9300/addversion.json", "when": "2019-12-20 14:45:16" }`

img：https://i.loli.net/2019/12/20/tAh8I7KXeT5BMWG.png

![tp](https://i.loli.net/2019/12/20/tAh8I7KXeT5BMWG.png)

This error often occurs when using "deploy project" in the scrapedweb.

Also, is self.timeout in \site-packages\scrapydweb\utils\poll.py the timeout to control the request addversion.json

**Comment by my8100** [comment]
You can adjust the timeout argument below. 
https://github.com/my8100/scrapydweb/blob/8104386438cb7e18e5b619c53aedf22dc5bb8954/scrapydweb/views/baseview.py#L274

**Comment by kjxy** [comment]
> You can adjust the timeout argument below.
> https://github.com/my8100/scrapydweb/blob/8104386438cb7e18e5b619c53aedf22dc5bb8954/scrapydweb/views/baseview.py#L274

There is no views directory on docker.
scrapydweb v 1.1.0

**Comment by my8100** [comment]
```
pip install -U scrapydweb
```
