### ISSUE TITLE
Timer tasks issue after adding a new node

### ISSUE THREAD

**Issue by JinxYuan** [my8100/scrapydweb#115]
Let's say I started with 5 nodes
([1]192.168.1.1:6800、
[2]192.168.1.2:6800、
[3]192.168.1.3:6800、
[4]192.168.1.4:6800、
[5]192.168.1.5:6800)
Timer Tasks  selected_nodes[1,2,3,4,5]
So let me add another node
10.168.1.1:6800
The node list will become
([1]10.168.1.1:6800、
[2]192.168.1.1:6800、
[3]192.168.1.2:6800、
[4]192.168.1.3:6800、
[5]192.168.1.4:6800、
[6]192.168.1.5:6800)
Before the Timer Tasks selected_nodes[1,2,3,4,5]
The corresponding is
([1]10.168.1.1:6800、
[2]192.168.1.1:6800、
[3]192.168.1.2:6800、
[4]192.168.1.3:6800、
[5]192.168.1.4:6800
)
Node 1 will report an error and cannot be found spider
Normal should be Timer Tasks selected_nodes[2,3,4,5,6]

**Comment by my8100** [comment]
Simply click the edit button to update your timer tasks after modifying the SCRAPYD_SERVERS option.

**Comment by JinxYuan** [comment]
Thank you very much!
I know this, because I have so many spiders, and it takes a long time to change one by one. I didn't know this problem when I first added node, so I reported an error
haha

**Comment by my8100** [comment]
You can also set up group info in SCRAPYD_SERVERS to avoid updating the existing timer tasks.
