### ISSUE TITLE
scrapydweb service is being killed frequently

### ISSUE THREAD

**Issue by HongWeiChen** [my8100/scrapydweb#117]
**Describe the bug**
Some features will cause the CPU soar to 100%, my centOS will automatically stop scrapydweb,  isn't my log content too much? I don't know why.

**To Reproduce**
1. Create project
2. Run any spider
3. After a while, click log, centOS CPU to 100% and will automatically kill my scrapydweb service :(

**Expected behavior**
Hope to optimize the log ..

**Logs**
Not any log, because scrapydweb is crash in any time, I don't crash log is where it.

**Screenshots**
not

**Environment (please complete the following information):**
 - OS: CentOS7.6
 - Python: 3.7
 - ScrapydWeb: 1.4.0
 - Scrapyd amount 2
 - Related settings Default
 - Browser Not, just Scrapy running

**Additional context**
Not

**Comment by my8100** [comment]
Click the Stats button instead of the Log button.
Also, remember to run logparser on any host running Scrapyd.
