### ISSUE TITLE
Can I launch the WebUI using a custom URL path

### ISSUE THREAD

**Issue by HongWeiChen** [my8100/scrapydweb#118]
Rt.

**Comment by my8100** [comment]
For example?

**Comment by HongWeiChen** [comment]
> For example?

Now the URL path is "/ 1 / xxx /" or / 2 / xxxx / This way, I want to change it to. "/ Pachong / 1 / xxx /" , I want to open as few ports as possible in CentOS, and use Nginx to forward

**Comment by my8100** [comment]
Try to update the below code, but it's not guaranteed.
```
            rule = '/Pachong/<int:node>/%s' % url if with_node else '/Pachong/%s' % url
```
https://github.com/my8100/scrapydweb/blob/8104386438cb7e18e5b619c53aedf22dc5bb8954/scrapydweb/__init__.py#L149
