### ISSUE TITLE
question about Scrapy Log Analysis 

### ISSUE THREAD

**Issue by toBetterMans** [my8100/scrapydweb#119]
hello boss:
  I have a question about the log analysis:I change my scrapy logs format and the Scrapy Log Analysis in my scrapydweb there is nothing.shoud I use  the log's Default Settings? Or someting shoud I to do ?
  thanks for helping.

**Comment by toBetterMans** [comment]
`LOG_FORMAT = '%(asctime)s-%(name)s:%(module)s%(filename)s[line:%(lineno)d]-%(funcName)s()-%(levelname)s-%(process)d-%(message)s'`

**Comment by my8100** [comment]
It's better to use the default format for the Scrapy log.
Otherwise, you may need to update re patterns in below source file of logparser:
https://github.com/my8100/logparser/blob/62c04516e93135e593ec302fe97a1a4b14a31cc2/logparser/common.py#L23-L30

**Comment by toBetterMans** [comment]
I get it .thank you a lot!
