### ISSUE TITLE
How to generate the files needed to update the code?

### ISSUE THREAD

**Issue by kjxy** [my8100/scrapydweb#120]
How to generate uploaded files in docker? Where to save the generated file?

![微信截图_20200109133206.png](https://i.loli.net/2020/01/09/AejV2qWziaYRg8r.png)

Thank you

**Comment by my8100** [comment]
Execute `pip install -U scrapydweb`, then check out the HELP section in the deploy page.

**Comment by kjxy** [comment]
> Execute `pip install -U scrapydweb`, then check out the HELP section in the deploy page.

An older version is required. Is it possible to use the file generated by the command "scraped deploy < target > - P < project >" (compress it)? Or how to generate files that can be uploaded? Thank you very much.

**Comment by my8100** [comment]
Check out the HELP section in the deploy page.
