### ISSUE TITLE
Timer tasks is too laggy to open.

### ISSUE THREAD

**Issue by crud-boy** [my8100/scrapydweb#121]
http://127.0.0.1:5000/1/tasks

The system network is not jammed, and there are not many tasks. Other tabs are opened normally. Just time the task option. It takes more than ten minutes to open

**Comment by my8100** [comment]
Can you upload a screenshot to show the details of your timer tasks. 
Besides, it’s recommended to set up xxx to use other da:
https://github.com/my8100/scrapydweb/blob/8104386438cb7e18e5b619c53aedf22dc5bb8954/scrapydweb/default_settings.py#L349-

**Comment by my8100** [comment]
duplicate, see #126
