### ISSUE TITLE
Could there be other python packages under my scrapy project？

### ISSUE THREAD

**Issue by lvouran** [my8100/scrapydweb#125]
I have other python packages under my scrapy project ，for example：test/[one python packages,  test]/spider/ [myspider.py,  other python packages]    when I delopy  the project,  can not recognition this spider，show the message： select version first （but select version  already）

**Comment by lvouran** [comment]
What should I do to solve this problem

**Comment by my8100** [comment]
Can you show me some screenshot to clarify the problem?
What if you deploy your spider manually?

**Comment by lvouran** [comment]
thanks， I sove it ,  spider name contains - listspider api return [] , so i changed my spider name
