### ISSUE TITLE
Regarding concurrent requests and process spawn

### ISSUE THREAD

**Issue by aysark** [my8100/scrapydweb#127]
I'm considering using crawlera+scrapy+scrapydweb.  I have setup my spider settings to have `CONCURRENT_REQUESTS = 100`

Now when i run jobs on scrapydweb, i am seeing that the CONCURRENT_REQUESTS the job is doing is much lower < 10.  Is there way to address this?  How does scrapydweb spawn jobs at an OS level, are these separate processes? 

Also do you have any tips on how one can increase count/min.  Currently getting 100 count/min with simple 200 status code requests with small json responses.  I switched to using ujson for json parsing but i want to remove it altogether and just do `yield response.text` but scrapy doesn't allow that.

**Comment by my8100** [comment]
Scrapydweb simply sends your command to Scrapyd in the background. 
Note that the option CONCURRENT_REQUESTS_PER_DOMAIN should be adjusted along with CONCURRENT_REQUESTS. 
https://docs.scrapy.org/en/latest/topics/settings.html#concurrent-requests-per-domain

**Comment by aysark** [comment]
Thank you @my8100 i noticed that i had that option commented out on this new project... will try it out!

Btw, is it possible to create a pipeline or sequence of Timer Tasks whereby they one will trigger only after a previous task has successfully completed?

**Comment by my8100** [comment]
There’s no connection between timer tasks.
Maybe you can try triggering a task in your spiders. (use Chrome DevTools to find the API.)
