### ISSUE TITLE
[BUG] 访问scrapyd的items接口返回404 

### ISSUE THREAD

**Issue by tomnattle** [my8100/scrapydweb#129]
**Describe the bug**
Oops! Something went wrong.
http://127.0.0.1:6800/items/
status_code: 404
<html>
  <head><title>404 - No Such Resource</title></head>
  <body>
    <h1>No Such Resource</h1>
    <p>No such child resource.</p>
  </body>
</html>

点击ui左侧的items 会出现404页面,目前我看了scrapyd的接口,没有items.

class ItemsView(BaseView):
    methods = ['GET']

    def __init__(self):
        super(ItemsView, self).__init__()

        self.project = self.view_args['project']
        self.spider = self.view_args['spider']

        self.url = 'http://{}/items/{}{}'.format(self.SCRAPYD_SERVER,
                                                 '%s/' % self.project if self.project else '',
                                                 '%s/' % self.spider if self.spider else '')
        if self.SCRAPYD_SERVER_PUBLIC_URL:
            self.public_url = re.sub(r'^http.*?/items/', self.SCRAPYD_SERVER_PUBLIC_URL + '/items/', self.url)
        else:
            self.public_url = ''
        self.template = 'scrapydweb/logs_items.html'
        self.text = ''

这个是scrapyd接口
https://github.com/scrapy/scrapyd/blob/4520c45acc115d0fc766eae30788468a77690433/scrapyd/webservice.py

**Comment by tomnattle** [comment]
版本号:
Scrapy           2.0.0
scrapyd          1.2.1
scrapydweb       1.4.0

**Comment by my8100** [comment]
You should set up the items_dir of Scrapyd first. 
https://scrapyd.readthedocs.io/en/stable/config.html#items-dir

**Comment by tomnattle** [comment]
3q
