### ISSUE TITLE
Run multiple spiders of a project at the same time

### ISSUE THREAD

**Issue by lx1054331851** [my8100/scrapydweb#130]
Hope newe feature: Deploy multiple spider at one time in one project? 
For example:
![image](https://user-images.githubusercontent.com/12423206/77870742-cc71bc00-7274-11ea-80b5-dddfc4215edb.png)
Hope multiple select spider to deploy.

**Comment by my8100** [comment]
Thanks for your suggestion. 
But I don’t think it’s a common practice. 
Maybe you can add some timer tasks to avoid running your spiders manually.

**Comment by lx1054331851** [comment]
Thank you for the awesome framework! I'll close the issue.
