### ISSUE TITLE
How to configure scrapydweb to run on Ubuntu EC2 and display at ec2 ip address

### ISSUE THREAD

**Issue by cyclehacker** [my8100/scrapydweb#131]
Thanks for the great project!

I've set up and run scrapydweb local and it work great. I'm now trying to set it up on an EC2 instance

What steps would I need to to take to deploy the app to the ip of the EC2 instance so that I can access it from my browser?

Many thanks,

**Comment by my8100** [comment]
Maybe you can refer to #73

**Comment by cyclehacker** [comment]
Thanks, I managed to figure it out!

**Comment by my8100** [comment]
Could you share your experience?

**Comment by cyclehacker** [comment]
It turns out I didn't manage to get it working.

I trying to run it on gunicorn like this: gunicorn -b 0.0.0.0:5000 scrapydweb.run:main

scrapyd is running on 127.0.0.1:6800
scrapydweb is set to run on 0.0.0.0:5000

I've tried multiple combinations of addresses but receive either site can't be reached or internal server errors.

I'm clearly missing something fundamental here.

**Comment by my8100** [comment]
I am not sure whether scrapydweb could work well with gunicorn. 
Maybe you should test it locally first,
or use nohup directly. 
You can use svr-6.herokuapp.com:80 as a scrapyd server for debugging.

**Comment by cyclehacker** [comment]
nohup is for running a unix job in the background, which I see might be useful once I get scrapyweb running in a production environment:

"WARNING: Do not use the development server in a production. "
 "Check out http://flask.pocoo.org/docs/1.0/deploying/"

Have you tested with any of the options on the above page? Or do you think it's not really going to work well in any of these environments?

**Comment by caffeinatedMike** [comment]
@cyclehacker the reason you're having using running this app with gunicorn is because the function that you're calling is running the app instance instead of returning it for gunicorn to handle. You can tweak this by returning the `app` variable from the function and that should allow the app to work properly with gunicorn and any other server libraries.

**Comment by Tobeyforce** [comment]
> @cyclehacker the reason you're having issues running this app with gunicorn is because the function that you're calling is running the app instance instead of returning it for gunicorn to handle. You can tweak this by returning the `app` variable from the function and that should allow the app to work properly with gunicorn and any other server libraries.


@caffeinatedMike Have you managed to deploy scrapydweb? I'm trying to return app but figuring out Flask work is giving me headache..
@cyclehacker Did you succeed in switching over to a prod server? Would you mind sharing what you did?
