### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by WalkOnMars** [my8100/scrapydweb#132]
I use scrpaydweb to deploy a project ,but occur following issue

----------------------------------------error show on screen---------------------------
Fail to deploy project, got status: error
{
    "auth": null,
    "message": "See details below",
    "status": "error",
    "status_code": -1,
    "url": "http://47.100.203.81:10071/addversion.json",
    "when": "2020-04-17 14:58:20"
}
Details
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

**Comment by WalkOnMars** [comment]
anyone have the some issue ? any help would be thanks

**Comment by WalkOnMars** [comment]
I can use scrapyd-deplay to upload project to server without any problem. but use scrapydweb auto-pack function is not ok.

**Comment by my8100** [comment]
Could you new a simplest Scrapy project and try again?

**Comment by WalkOnMars** [comment]
other project is fine, only this project have this issue, this really strange, I don't know what's wrong with this project ?  I have search google ,but can't found any constructive advise.

**Comment by my8100** [comment]
Did you get an egg file after using scrapyd-deplay?
If yes, what if you upload the egg file via scrapydweb?
