### ISSUE TITLE
[BUG] Too many jobs in the dashboard

### ISSUE THREAD

**Issue by codehia** [my8100/scrapydweb#134]
There are too many jobs in the dashboard all the completed ones as well, and all the jobs are sorted by the date in the order where the oldest jobs come first.

I use GIT version with `scrapyd-deploy`  to deploy the spiders, and a custom command to run the crawl.

**Comment by my8100** [comment]
1. You can set up the below option:
https://github.com/my8100/scrapydweb/blob/12c48923dd64bbef3c8db2bd40c93d1854ebd46f/scrapydweb/default_settings.py#L174-L177
2. As the demo website shows, the latest jobs come first. 
http://scrapydweb.herokuapp.com/1/jobs/?style=classic
