### ISSUE TITLE
Scrapydweb is not running the spider automatically as planned

### ISSUE THREAD

**Issue by talbiislam96** [my8100/scrapydweb#136]
i scheduled   my spider to run  every day from monday to friday at 8pm however when i checked my database , i noticed that the data has been added only one time (my spider is programmed to scrape 60 items everytime i run it) am using mongo and before using scrapyweb i already had 120 documents , when i checked (after 3 days) there was 180 documents so it only run the spider  automatically one time.How can i fix this ? i really need an answer as soon as possible and thanks in advance.

**Comment by my8100** [comment]
Can you visit the Timer Task page and click the timer task you mentioned to show its details, then post a screenshot?

**Comment by talbiislam96** [comment]
![hello](https://user-images.githubusercontent.com/47306941/81487456-d82da680-9254-11ea-88aa-2a1512860179.PNG)
This is my first  time task it worked at first just fine (sometimes it works when i run the server others it doesn't) now it's not working at all 
so i replaced it with three time tasks here are the details
![errrr2](https://user-images.githubusercontent.com/47306941/81487543-15deff00-9256-11ea-8797-26087944bcc8.PNG)

am trying to run the same spider so it would scrape the website 
 i chose three times a day without me running any server and add the data to my database here are the details of every time task :
![detail1](https://user-images.githubusercontent.com/47306941/81487580-6c4c3d80-9256-11ea-9ec9-fbef7157287b.PNG)
![detail2](https://user-images.githubusercontent.com/47306941/81487582-73734b80-9256-11ea-8046-b45b9392fdaa.PNG)
![detail3](https://user-images.githubusercontent.com/47306941/81487583-78d09600-9256-11ea-9472-892ae6549293.PNG)

and this is the message i get in my console 
![errrrrrrrr](https://user-images.githubusercontent.com/47306941/81487587-8423c180-9256-11ea-9d46-02e68c5459e9.PNG)
The data is not added to my db when i last checked and the time task only works when i run the scrapyd server .How can i make my spider run automatically even once a day without me running any server because that is the purpose of the project am working on ? and thanks in advance

**Comment by my8100** [comment]
> How can i make my spider run automatically even once a day without me running any server

ScrapydWeb is a web app for Scrapyd management, so you have to keep your Scrapyd server running.
