### ISSUE TITLE
database_url doesn't working in version 1.4.0

### ISSUE THREAD

**Issue by OKCrash** [my8100/scrapydweb#141]
**Describe the bug**

I want to use mysql to replace sqlite , now scrapydweb running in docker on port 5000 by dtabase_url :
DATABASE_URL = os.environ.get('DATABASE_URL', 'mysql://username:pwd@218.xxx.xxx.xxx:3306')

but the config file seems not working :
![image](https://user-images.githubusercontent.com/5916725/81518715-829aec00-9371-11ea-8d8c-b61ffe35856f.png)

also there isn't any warning or error logs i can figure it out.

please help me out!

**To Reproduce**
3. See error

**Expected behavior**

**Logs**
Add logs of ScrapydWeb and Scrapyd (optional) when reproducing the bug.
(It's recommended to run ScrapydWeb with argument '--verbose' if its version >= 1.0.0)

**Screenshots**

**Environment (please complete the following information):**
 - Operating system: [e.g. Win 10, macOS 10.14, Ubuntu 18, centOS 7.6, Debian 9.6 or Fedora 29]
 - Python version: [e.g. 2.7 or 3.7]
 - ScrapydWeb version: [e.g. 1.4.0 or latest code on GitHub]
 - ScrapydWeb related settings [e.g. 'ENABLE_AUTH = True']
 - Scrapyd version: [e.g. 1.2.1 or latest code on GitHub]
 - Scrapyd amount [e.g. 1 or 5]
 - Scrapy version: [e.g. 1.8.0, 2.0.0 or latest code on GitHub]
 - Browser [e.g. Chrome 71, Firefox 64 or Safari 12]

**Additional context**

**Comment by my8100** [comment]
Same as #100, you can install the latest git version:
```
pip install --upgrade git+https://github.com/my8100/scrapydweb.git
```

**Comment by zhoumac** [comment]
git 地址 下拉不下来
