### ISSUE TITLE
How to solve the problem of Chinese scrambling in logs and items 

### ISSUE THREAD

**Issue by LuanShiZhiJian** [my8100/scrapydweb#148]
**Describe the bug**
Logs：
![image](https://user-images.githubusercontent.com/41558924/83109684-637fb680-a0f4-11ea-996f-f665f3d78aa1.png)

Items：
![image](https://user-images.githubusercontent.com/41558924/83109665-5793f480-a0f4-11ea-99a1-3928db0e57a8.png)

please suggest, Thanks

**Expected behavior**
Display Chinese content normally

**Environment (please complete the following information):**
Operating system:Win 10,
Python version: 3.7
ScrapydWeb version: 1.4.0
ScrapydWeb related settings ENABLE_AUTH = True
Scrapyd version: 1.2.1
Scrapyd amount :1
Scrapy version: 1.6.0
Browser :Chrome 81

**Comment by my8100** [comment]
It’s not an issue of scrapydweb.
You may refer to https://docs.scrapy.org/en/latest/topics/feed-exports.html?highlight=encoding#std-setting-FEED_EXPORT_ENCODING

**Comment by LuanShiZhiJian** [comment]
> It’s not an issue of scrapydweb.
> You may refer to:
> https://docs.scrapy.org/en/latest/topics/request-response.html?highlight=encoding#scrapy.http.TextResponse.text
> 
> https://docs.scrapy.org/en/latest/topics/feed-exports.html?highlight=encoding#std-setting-FEED_EXPORT_ENCODING

I don't seem to find a way and started this spider alone, the coding looks normal
