### ISSUE TITLE
Auto eggifying sets the folder name as the project name

### ISSUE THREAD

**Issue by seuarnaldo** [my8100/scrapydweb#15]
Congratulations on your work. I started using it and I hope to contribute with the project.

One problem I noticed is that by using the 'auto eggifying' feature, the project name is set to the folder name where there is a scrapy.cfg file. 
This can cause problems. It should be the name that is in the scrapy.cfg file (e.g. 'project = xxx').

**Comment by my8100** [comment]
Thanks for your advice.
This behavior has been fixed in the coming release, though it works fine in most cases.

**Comment by my8100** [comment]
v1.0.0 released: Parse project name from scrapy.cfg instead of setting it to the folder name for auto eggifying.
Get it via the `pip install -U scrapydweb` command.
