### ISSUE TITLE
ScrapydWeb overrides setup.py

### ISSUE THREAD

**Issue by piyusht007** [my8100/scrapydweb#166]
Hi @my8100,
I have a use case where I would like to include data files (.json, .txt etc) to the **egg** however when I am adding `include_package_data=True` to the `setup.py` it is not taking effect due to the fact that **ScrapydWeb** generates a new **setup.py** to create egg.

Any suggestions to achieve that? 

To add more context, I am deploying the project from ScrapydWeb User Interface using **Deploy Project >> Auto packaging**

**Comment by my8100** [comment]
You can comment out the below code:
https://github.com/my8100/scrapydweb/blob/6b9663b275dbb312a97f2819bf657dd0a3cc80c8/scrapydweb/views/operations/scrapyd_deploy.py#L62

Or update the default content of the new generated setup.py:
https://github.com/my8100/scrapydweb/blob/6b9663b275dbb312a97f2819bf657dd0a3cc80c8/scrapydweb/views/operations/scrapyd_deploy.py#L18-L29
