### ISSUE TITLE
A very important improvement

### ISSUE THREAD

**Issue by jueshiyizhimao** [my8100/scrapydweb#167]
I hope add a column in the picture below, name is "label" or "tag". Because my some projects belong to a requirement,It's could let me clearly see the status of each requirement.
Also,if could support the chinese or other non-English codes,so much the better.
I think this improvement could help a lot of people.

thank you very much!

![image](https://user-images.githubusercontent.com/26734950/97274656-ed80a680-186f-11eb-8ab3-d3f40838e93f.png)

**Comment by my8100** [comment]
I think you could make use of the project or spider names.
