### ISSUE TITLE
Getting error "HTTP status code is not handled or not allowed" after project deployed

### ISSUE THREAD

**Issue by duongtdvn** [my8100/scrapydweb#168]
**Describe the bug**
I have tried to run the spider via CLI and everything went fine, no error at all and it return expected items. But after deploy and run the spider via web interface i am getting "HTTP status code is not handled or not allowed".

**To Reproduce**
1. Deploy project
2. Run the spider

**Expected behavior**
Expect to have everything run like CLI.

**Logs**
```
2020-11-05 16:01:18 [scrapy.core.engine] DEBUG: Crawled (400) <POST https://domain.com> (referer: None)
2020-11-05 16:01:18 [scrapy.spidermiddlewares.httperror] INFO: Ignoring response <400 https://domain.com>: HTTP status code is not handled or not allowed
2020-11-05 16:01:18 [scrapy.core.engine] INFO: Closing spider (finished)
```

**Screenshots**

**Environment (please complete the following information):**
 - Operating system: [Ubuntu 20]
 - Python version: [3.8]
 - ScrapydWeb version: [latest code on GitHub]
 - ScrapydWeb related settings [e.g. 'ENABLE_AUTH = False']
 - Scrapyd version: [latest code on GitHub]
 - Scrapyd amount [e.g. 1 or 5]
 - Scrapy version: [latest code on GitHub]

**Additional context**

**Comment by my8100** [comment]
"HTTP status code is not handled or not allowed" is not found in your log.

**Comment by duongtdvn** [comment]
So, could it be issue from scrapyd right? as i can run fine through CLI.

**Comment by my8100** [comment]
You should figure out why your spider got the status code 400 from the target website.
