### ISSUE TITLE
WARNING: Do not use the development server in a production environment.   Use a production WSGI server instead.

### ISSUE THREAD

**Issue by versionzhang** [my8100/scrapydweb#17]
First, thanks for your awesome project.

every time when I run `scrapydweb` command , the warning message would show this in the terminal.

I think whether you can add some guide links for this warning.  such as [official deploy link](http://flask.pocoo.org/docs/1.0/deploying/). Just add information for someone who may confuse this message. It is not a bug,  just  an  optional improvement, so it is low priority thing.

Thanks.

**Comment by my8100** [comment]
Fixed in v1.1.0
