### ISSUE TITLE
[Feature request] Add error/warning counts to jobs table

### ISSUE THREAD

**Issue by adriandelarco** [my8100/scrapydweb#173]
It would be great to have the option to show errors/Warnings etc in the main jobs table, then without checking one by one, you could see if there are any errors or everything is fine.

In this table I mean:

![image](https://user-images.githubusercontent.com/9353018/103294905-0f72e280-49f3-11eb-9fd3-179299eab833.png)

**Comment by my8100** [comment]
It’s supported in the Node Reports page:
http://scrapydweb.herokuapp.com/1/nodereports/

**Comment by adriandelarco** [comment]
Thanks for the answer @my8100 

But do you know how to make Node reports to work? All the fields are empty for me, just as in the example link you link to.

![image](https://user-images.githubusercontent.com/9353018/103438083-50573b00-4c2f-11eb-9238-4b658fb686eb.png)

**Comment by my8100** [comment]
The link works normally in my network. 
You may press F12 in Chrome to see whether there are any errors.

**Comment by adriandelarco** [comment]
It's true. **uBlock Origin** extension was the problem.

Thank you.
