### ISSUE TITLE
SQL Alchemy 1.4 not supported, throws error

### ISSUE THREAD

**Issue by Tobeyforce** [my8100/scrapydweb#178]
Attempting to run Scrapydweb with the latest SQLAchemy (1.4 as of now) which is added when running pip install scrapydweb, throws errors.
Rolling back to 1.3.2 fixed it for me.

**Comment by mxdev88** [comment]
What database backend are you using? if postgresql, sqlalchemy removed in 1.4 support for URLs of the form `postgres://` for `postgresql://`. [see this](https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html#change-3687655465c25a39b968b4f5f6e9170b).

**Comment by Tobeyforce** [comment]
This was just based on the default db that comes with scrapydweb, I noticed I got errors thrown when pulling from github and following the instructions (whereas  it previously never was a problem). Might be fixed now, no clue :)

**Comment by johannesstricker** [comment]
Can confirm this. Rolling back to 1.3.2 worked for me as well 👍
