### ISSUE TITLE
Are there plans to support key-based SFTP authentication?

### ISSUE THREAD

**Issue by Noexpert** [my8100/scrapydweb#180]
Hi,

as above, unless I'm mistaken, only password authentication is supported.
Could key based authentication also be implemented?

Thanks

**Comment by my8100** [comment]
`SFTP provides an alternative method for client authentication. It's called SFTP public key authentication. This method allows users to login to your SFTP service without entering a password and is often employed for automated file transfers. `

Could you tell me why an Web App need SFTP?

**Comment by Noexpert** [comment]
OK closing. I'll go back and research further.
Thanks
