### ISSUE TITLE
scrapydweb_settings_v10.py的DATABASE_URL修改不生效

### ISSUE THREAD

**Issue by SekyGrande** [my8100/scrapydweb#182]
**Describe the bug**
scrapydweb_settings_v10.py的DATABASE_URL修改不生效

**To Reproduce**

1. 修改scrapydweb_settings_v10.py的DATABASE_URL
2. 在当前目录执行scrapydweb

**Expected behavior**
同目录的scrapydweb_settings_v10.py修改DATABASE_URL不生效，但是在/usr/local/lib/python3.9/site-packages/scrapydweb的default.settings修改，就生效了

**Environment (please complete the following information):**
 - Python version: [3.9]

**Comment by my8100** [comment]
#100
