### ISSUE TITLE
[BUG] 'pip install logparser' on the current Scrapyd host 

### ISSUE THREAD

**Issue by cjr0707** [my8100/scrapydweb#22]
**Describe the bug**
Running (0) 'pip install logparser' on the current Scrapyd host and get it started via command 'logparser' to show crawled_pages and scraped_items.

**To Reproduce**
1. Go to 'http://ip:5000/1/dashboard/'
2. See error

**Expected behavior**
Running (0) by LogParser: xxx seconds ago

**Screenshots**
![](https://ws1.sinaimg.cn/large/006tNc79ly1g03m9lkaepj31t80l4wkj.jpg)

**Environment (please complete the following information):**
 - OS: centOS 7.6
 - Python: 3.6.6
 - Browser Chrome 71

**Additional context**
I am sure I have pip install logparser this machine(A). In another machine, I can use it normally, and use this requirements.txt to pip in machine(A).

**Comment by my8100** [comment]
Did you forget to run the command 'logparser' on the machine (A)?

**Comment by cjr0707** [comment]
POST http://172.18.19.134:5000/1/api/liststats/
text:
{
    "status": "error",
    "message": "\n<html>\n  <head><title>404 - No Such Resource</title></head>\n  <body>\n    <h1>No Such Resource</h1>\n    <p>File not found.</p>\n  </body>\n</html>\n",
    "url": "http://ip:6800/logs/stats.json",
    "auth": null,
    "status_code": 404,
    "when": "2019-02-12 14:37:51",
    "tip": "'pip install logparser' on the current Scrapyd host and get it started via command 'logparser'"
}

I run scrapydweb and scrapyd in machine(A) ,also run scrapyd in error machine.
SCRAPYD_LOGS_DIR--> set the same path.
machine(A) can normally use, but error machine can't.

**Comment by my8100** [comment]
Is LogParser running on the error machine?

**Comment by cjr0707** [comment]
Oh...thanks, solved...
I thought that only one machine start scrapydweb, other machines just start scrapyd...
