### ISSUE TITLE
Processes dont stop after finishing

### ISSUE THREAD

**Issue by danyanyam** [my8100/scrapydweb#220]
Hi!

Thanks for an awesome project! It is really great and helpful!

Recently i faced with the following problem: 

![Снимок экрана 2023-09-04 в 13 38 40](https://github.com/my8100/scrapydweb/assets/48715538/6d07d568-7a5a-4882-92c0-73f8a28fcf18)
I have several crawls started, they finished with some reason and processes didnt stop (green buttons didnt turn blue automatically). I have to manually stop them in the "Jobs" page

**Comment by my8100** [comment]
Hi, the color of the Stats button depends on the job state (Pending|Running|Finished).
