### ISSUE TITLE
ERROR: Package 'scrapydweb' requires a different Python:

### ISSUE THREAD

**Issue by ilcaa72** [my8100/scrapydweb#225]
i am using Python3.9.18

what is proper version of python to use with scrapydweb?

or how do i resolve this error

ERROR: Package 'scrapydweb' requires a different Python: 3.9.18

**Comment by my8100** [comment]
Please have a try for the latest scrapydweb v1.4.1, which supports Python 3.6 to 3.9

**Comment by omisolaidowu** [comment]
Are you planning an upgrade for Pyhon 3.10+?

**Comment by my8100** [comment]
Python 3.10 to 3.12 are already supported in PR https://github.com/my8100/scrapydweb/pull/227
