### ISSUE TITLE
Error while installing scrapydweb

### ISSUE THREAD

**Issue by moya1295** [my8100/scrapydweb#226]
When I try to install scrapydweb in my virtual env on ubuntu linux the error is as follows:
ERROR: Package 'scrapydweb' requires a different Python: 3.10.9 not in '!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,!=3.5.*,<=3.9,>=2.7'

The command i used to install is as follows:
pip install --upgrade git+https://github.com/my8100/scrapydweb.git

My Python version = 3.10.9
My OS :
Distributor ID: Ubuntu
Description:    Ubuntu 23.10
Release:        23.10
Codename:       mantic

is there any fix to install without downgrading my python version, I dont want to break other things in my code.

Apologies in advance for bad formatting if any, it is my first issue on github.

**Comment by my8100** [comment]
Python 3.10 to 3.12 are already supported in PR https://github.com/my8100/scrapydweb/pull/227

**Comment by my8100** [comment]
Fixed in v1.5.0
