### ISSUE TITLE
DATABASE_URL配置连接域名:端口的mysql失败

### ISSUE THREAD

**Issue by zhouchengzhi1994** [my8100/scrapydweb#232]
DATABASE_URL配置连接域名:端口的mysql失败
scrapydweb版本1.4.0
有大佬遇到过这个问题，知道怎么解决吗
之前连接ip:3306端口的mysql是成功的

**Comment by my8100** [comment]
Please use the latest version v1.5.0 and post the related log.

**Comment by zhouchengzhi1994** [comment]
it is OK that using v1.4.1 and v1.5.0, thank you very much
