### ISSUE TITLE
When i visiting items page i got "Oops! Something went wrong.".

### ISSUE THREAD

**Issue by fatih-dev-ops** [my8100/scrapydweb#234]
**Describe the bug**
When i visiting the items page i got an error 404 "Oops! Something went wrong.
".  I examined the issues and scrapyd configuration file for items_dir but i didn't any solutions.

**Expected behavior**
When i changed the items dir for scrapyd it gave me different results. Firstly when i give a specific items dir, I get the error above in the **Describe the Bug**. Secondly I gave the "items" for items dir, it didn't save items log in items dir but I didn't get the error above in **Describe the Bug**.
**Screenshots**
![image](https://github.com/user-attachments/assets/63d73bfd-f6d8-4bae-a330-16a100978205)

**Additional context**
So how can i solve this problem?

**Comment by my8100** [comment]
See #129
