### ISSUE TITLE
How create/change timer_task manually by db?

### ISSUE THREAD

**Issue by asenatorrr** [my8100/scrapydweb#237]
I want to change time of a timer task. I have tried to do it with 'task' table of  'timer_tasks.db', but it hasn't any effect, only changes of settings in GUI of Timer Tasks tab. Can I force to apply changes?
P.S. I need to change about 30 timer tasks, that's why I want to do it by console command.

**Comment by my8100** [comment]
It’s not recommended to modify the db manually. 
You may simulate the request sent by the browser.

**Comment by asenatorrr** [comment]
Yes, I restarted after modifying, but it didn't work.
Can you give any example of simulating of a request? I'm confused a little about it.

**Comment by my8100** [comment]
FYI
https://stackoverflow.com/questions/42115727/how-to-programmatically-replicate-a-request-found-in-chrome-developer-tools
