### ISSUE TITLE
排序失效

### ISSUE THREAD

**Issue by meteor-nb** [my8100/scrapydweb#248]
**Describe the bug**
scrapyd升级1.5.0后，jobs-classic页面的Finished列表DESC排序失效

**Screenshots**
![screenshot_2024-11-25_13-01-29](https://github.com/user-attachments/assets/d7de859e-74ee-43f0-985a-7bfd6ba9e717)

**Environment:**
 - Operating system: centOS 7.6
 - Python version: 3.8
 - ScrapydWeb version: 1.5.0
 - Scrapyd version: 1.5.0

**Additional context**
scrapyd 1.5.0之前是正常的，升级后排序失效

**Comment by my8100** [comment]
Please try this version:

`pip install git+https://github.com/my8100/scrapydweb.git@bugfix_for_scrapyd_v150`

**Comment by meteor-nb** [comment]
> Please try this version:
> 
> `pip install git+https://github.com/my8100/scrapydweb.git@bugfix_for_scrapyd_v150`

Thanks, this version can be sorted properly, awesome!

**Comment by my8100** [comment]
Fixed in v1.5.2 (https://github.com/my8100/scrapydweb/pull/252)
