### ISSUE TITLE
How to restart this application more elegantly?

### ISSUE THREAD

**Issue by clown-0726** [my8100/scrapydweb#27]
How to restart this application more elegantly?

and when this app can intergrade a function which can be used to schedule spider/spiders?  think this kind of fun will be very helpful.

**Comment by my8100** [comment]
1. Why do you need to restart the application? Just run it as a service like Scrapyd. Could you show me some examples which restart elegantly?
2. It's just around the corner.

**Comment by my8100** [comment]
v1.2.0: Support Timer Tasks
