### ISSUE TITLE
Email send failed, suggest split FROM_ADDR and EMAIL_USER

### ISSUE THREAD

**Issue by Jason-Liu-Dream** [my8100/scrapydweb#28]
Dear friend,
    I am very like you scrapydweb project, and use it in many place. But today I found email sender not  support our school's mailbox，becourse our school email login user name is different 'from_addr' , and it not cotains suffix string like '@xxx.edu.com'. I suggest split FROM_ADDR and EMAIL_USER, and change 'smtp.login(from_addr, ...)' to 'smtp.login(email_user)'. 
   Thanks.

**Comment by my8100** [comment]
Does it really work after you changed `server.login(from_addr, email_password)` to `server.login('username', email_password)` in send_email.py?
https://github.com/my8100/scrapydweb/blob/acbfa5c58bfc3053dd0bfafdd45531f58f5d1a7e/scrapydweb/utils/send_email.py#L44

**Comment by my8100** [comment]
Thanks for your suggestion, and it has been supported in the coming release.

**Comment by Jason-Liu-Dream** [comment]
Yes, I change my code to replace username and it send email success.

**Comment by my8100** [comment]
v1.2.0: Support setting up EMAIL_USERNAME separately
