### ISSUE TITLE
Could not find a version that satisfies the requirement scrapydweb==1.2.0

### ISSUE THREAD

**Issue by po-boy** [my8100/scrapydweb#31]
Could not find a version that satisfies the requirement scrapydweb==1.2.0 (from versions: 0.9.1, 0.9.2)  
why

**Comment by my8100** [comment]
Try `pip install --upgrade pip` first, or install ScrapydWeb via git instead.

**Comment by my8100** [comment]
https://stackoverflow.com/questions/14617136/why-is-pip-installing-an-old-version-of-my-package

**Comment by po-boy** [comment]
![图片](https://user-images.githubusercontent.com/23032525/54796996-6e87bd00-4c8d-11e9-8d72-c47778772e1e.png)
![图片](https://user-images.githubusercontent.com/23032525/54797009-77788e80-4c8d-11e9-844a-c29cc8bfd11c.png)

**Comment by my8100** [comment]
Try to restart the Scrapyd service first.

**Comment by my8100** [comment]
Try to restart the Scrapyd service first. Or you may need to create the `eggs` folder manually. https://scrapyd.readthedocs.io/en/latest/config.html#eggs-dir

**Comment by po-boy** [comment]
Thanks so much.
