### ISSUE TITLE
How does ScrapydWeb handle route?

### ISSUE THREAD

**Issue by spider-study** [my8100/scrapydweb#32]
Hello, you're doing great. I'm a beginner of flask. I've been playing with crawlers. I rarely touch web frameworks. I want to know that I want to add a new function, such as creating crawler files on the web side and deploying them directly into scrapydweb. How can I add a route to guide links? Which is your route add. py, I don't know where to add my xx. HTML route! Maybe I asked this is silly, but I am a beginner, and I don't know the framework yet. I hope to give you an answer! Thank you very much.

**Comment by spider-study** [comment]
I've written it. Several HTML files let him create srapy files automatically and deploy them to scrapyd automatically. But I want to add this to your interface because the front end I write is too low. So I want to open it directly to you. Then I click on a link and jump to my automatic add page. I don't know where to add my route.

**Comment by my8100** [comment]
https://github.com/my8100/scrapydweb/blob/c2fb2d049e0bbfbbc156bb8b79b2a3b527956477/scrapydweb/__init__.py#L143

**Comment by spider-study** [comment]
Can I add models. py file to this? Then map the database as a whole?

**Comment by my8100** [comment]
Go ahead and debug by yourself.
