### ISSUE TITLE
how to deploy scrapydweb by github resp

### ISSUE THREAD

**Issue by fightingpjh** [my8100/scrapydweb#34]
on heroku.com, I set myscrapydweb's Deployment method to "github"（I forkd https://github.com/my8100/scrapydweb to :https://github.com/fightingpjh/scrapyWeb）, connect  this app to GitHub (https://github.com/fightingpjh/scrapyWeb), then the server breakdown,  request the addr myscrapydweb.heroku.com by chrome failed!   
        so,  how can i deploy the scrapyweb by github resp?

**Comment by my8100** [comment]
It's not an issue of ScrapydWeb, please turn to https://devcenter.heroku.com/articles/getting-started-with-python for help.
