### ISSUE TITLE
the scrapyd server port issue

### ISSUE THREAD

**Issue by fightingpjh** [my8100/scrapydweb#36]
in this https://github.com/my8100/scrapyd-cluster-on-heroku-scrapyd-app repo, thd init.py file set the scrapyd port 6800 by this:
PORT = int(os.environ.get('PORT', 6800))
with io.open("scrapyd.conf", 'r+', encoding='utf-8') as f:
    f.read()
    f.write(u'\nhttp_port = %s\n' % PORT)

when i deployed Scrapyd server on heroku.com :
telnet pjhscrapyd1.heroku.com 6800 Failed
telnet pjhscrapyd1.heroku.com 6801 Failed
telnet pjhscrapyd1.heroku.com 80 Succeed

what's wrong with it?

**Comment by my8100** [comment]
Please submit the issue in repo [scrapyd-cluster-on-heroku-scrapyd-app](https://github.com/my8100/scrapyd-cluster-on-heroku-scrapyd-app/issues)
