### ISSUE TITLE
Use Timer Tasks to start crawling jobs concurrently

### ISSUE THREAD

**Issue by CoderZHV** [my8100/scrapydweb#37]
我创建了两个timer task,  都是5秒执行一次， 两个定时任务在相同时间只有一个会被执行， 怎样才能实现多个job并发执行， 是bug还是我的设置有问题？ 望解惑 多谢

**Comment by my8100** [comment]
Please provide the screenshots of the detais of your tasks in the Timer Tasks page, as well as necessary logs.

**Comment by CoderZHV** [comment]
![image](https://user-images.githubusercontent.com/13792304/56402956-ffa08280-6291-11e9-8ec4-8f078ca007dd.png)
![image](https://user-images.githubusercontent.com/13792304/56403027-370f2f00-6292-11e9-89ef-08e0c1c49f6e.png)
![image](https://user-images.githubusercontent.com/13792304/56403138-9c632000-6292-11e9-8041-7c3d8e456839.png)
图二看出 task1 与 task2 交替执行 五秒执行一次  同一个task开始时间间隔十秒  但是 我创建task时设置的是同一个task 5秒执行一次

**Comment by my8100** [comment]
As you can see from the Job column, both task#1 and task#2 are being executed every 5 seconds, whereas the Start column indicates the actual start time of the crawling jobs. 
Apparently, **the Scrapyd server is too busy to start the job as soon as the task is executed**, which could be confirmed by checking whether there are any pending jobs on the Jobs page. 
Also, see https://scrapyd.readthedocs.io/en/latest/config.html#max-proc to find out the maximum number of concurrent Scrapy process that will be started. And such info could be found when you launch the Scrapyd service:
```
2019-04-19T11:28:32+0800 [Launcher] Scrapyd 1.2.0 started: max_proc=16, runner='scrapyd.runner'
```

**Comment by my8100** [comment]
You also need to adjust [poll_interval](https://scrapyd.readthedocs.io/en/latest/config.html#poll-interval)
```
The interval used to poll queues, in seconds. Defaults to 5.0. Can be a float, such as 0.2
```
