### ISSUE TITLE
I hope to support the following features

### ISSUE THREAD

**Issue by tuchief** [my8100/scrapydweb#4]
1、Timed task
2、Online packaging and deployment
3、Log monitoring alarm

**Comment by my8100** [comment]
@tuchief 

> 2、Online packaging and deployment

Have you tried the Projects > Deploy page?

**Comment by tuchief** [comment]
I know what you said, but this method should be manually packaged into egg, and then uploaded, and can not directly package the source project into egg, automatically upload it?

**Comment by tuchief** [comment]
You can refer to https://github.com/Gerapy/Gerapy

**Comment by my8100** [comment]
v0.9.9: Add auto eggifying

**Comment by tuchief** [comment]
Wow, the response is fast! Expecting the same timing tasks

**Comment by wymen2018** [comment]
1. You can select multiple crawlers when you want to set a timed task. You can select multiple crawlers to start at each time period after selecting the time point.
Imagine that I have 100 crawlers in a project. This feature does provide convenience and management.
2, as above, because there are a hundred crawlers, so can you have the function of custom label, that is, I can use the label screen and view the running status of the specified category of crawlers, and timed tasks
Thanks!

**Comment by my8100** [comment]
> You can select multiple crawlers when you want to set a timed task. You can select multiple crawlers to start at each time period after selecting the time point.
> Imagine that I have 100 crawlers in a project. This feature does provide convenience and management.

You mean there are 100 spiders in a project and you want to schedule some of them to run periodically? 

> as above, because there are a hundred crawlers, so can you have the function of custom label, that is, I can use the label screen and view the running status of the specified category of crawlers, and timed tasks

What about labeling some related jobs with a specific jobid?

**Comment by wymen2018** [comment]
>> You mean there are 100 spiders in a project and you want to schedule some of them to run periodically?
>
>No, Simultaneously select multiple spiders to set one timed task.
> 
>> What about labeling some related jobs with a specific jobid?
>
>Labels will be better because they can be more visualized according to their own classification

**Comment by my8100** [comment]
OK, I would take it into account when implementing this feature. Thanks for your advice!

**Comment by my8100** [comment]
v1.0.0rc1: Add Email Notice
Get it with command: `pip install scrapydweb==1.0.0rc1`

**Comment by LWsmile** [comment]
ERROR in utils: !!!!! ConnectionError HTTPConnectionPool(host='127.0.0.1', port=6800): Max retries exceeded with url: /jobs (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f6111cae9b0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by my8100** [comment]
> ERROR in utils: !!!!! ConnectionError HTTPConnectionPool(host='127.0.0.1', port=6800): Max retries exceeded with url: /jobs (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f6111cae9b0>: Failed to establish a new connection: [Errno 111] Connection refused',))

Please new an issue with details.

**Comment by my8100** [comment]
> > You mean there are 100 spiders in a project and you want to schedule some of them to run periodically?
> 
> No, Simultaneously select multiple spiders to set one timed task.
> 
> > What about labeling some related jobs with a specific jobid?
> 
> Labels will be better because they can be more visualized according to their own classification

@wymen2018 The new feature **Timer task**  is about to be supported in the next release. Could you explain your demands with example, maybe in Chinese?

**Comment by lidonghe** [comment]
timed task +1

**Comment by my8100** [comment]
v1.2.0: Support Timer Tasks

**Comment by lidonghe** [comment]
While adding a timer task, I have to choose a version, but actually I only want to use the latest version so that if the project is updated, I don't need to update my task accordingly.

**Comment by my8100** [comment]
OK, it would be fixed in the future release.
For the time being, go to the Jobs page and click either **multinode** or **Start** button to work around.

**Comment by my8100** [comment]
Or modify the code below to `vm.versions = ['default: the latest version'].concat(obj.versions);`
https://github.com/my8100/scrapydweb/blob/560e998628839ca0de741a467b9176043378bbf1/scrapydweb/templates/scrapydweb/schedule.html#L826

**Comment by lidonghe** [comment]
> Or modify the code below to `vm.versions = ['default: the latest version'].concat(obj.versions);`
> [scrapydweb/scrapydweb/templates/scrapydweb/schedule.html](https://github.com/my8100/scrapydweb/blob/560e998628839ca0de741a467b9176043378bbf1/scrapydweb/templates/scrapydweb/schedule.html#L826)
> 
> Line 826 in [560e998](/my8100/scrapydweb/commit/560e998628839ca0de741a467b9176043378bbf1)
> 
>                              vm.versions = obj.versions;

It works, thanks

**Comment by my8100** [comment]
The modification has been commited.

**Comment by heave-Rother** [comment]
For Logs categorization, can the same spiders distributed on different scrapyd be aggregated? @my8100

**Comment by my8100** [comment]
@heave-Rother 
For the time being, you can **switch to a specific page of the neighboring node**
with the help of Node Scroller and Node Skipping.
![image](https://user-images.githubusercontent.com/37427675/61762778-a3f01300-ae05-11e9-982b-2e32d72d97a3.png)

If that cannot satisfy your need, could you draw a picture to show me your idea?

**Comment by heave-Rother** [comment]
@my8100 ok,
![捕获](https://user-images.githubusercontent.com/35719635/61768654-a1e47f00-ae1a-11e9-9654-ba8c54ccd535.PNG)

**Comment by my8100** [comment]
@heave-Rother 
1. What would you use the checkboxes in the drop-down list for? 
Did you notice the checkboxes for nodes in the Servers page?
2. Stats aggregation would be followed up in PR #72.

**Comment by heave-Rother** [comment]
@my8100 
yes, I want to choose the server I want to join the statistics.

**Comment by my8100** [comment]
@heave-Rother 
I see. Thanks for your suggestion.

**Comment by seozed** [comment]
add a image of docker, please

**Comment by my8100** [comment]
> add a image of docker, please

@seozed 
Check out the [docker image](https://hub.docker.com/r/chinaclark1203/scrapydweb) created by @luzihang123.

https://github.com/my8100/logparser/issues/15#issuecomment-522967794

**Comment by devxiaosong** [comment]
感谢作者，这是我找到的最好的爬虫集群操作平台。提几个需求：
1，给每个node加描述，方便自己看。
2，通过手机短信发送报警信息。
3，如何支持基于scrapy-redis的分布式爬虫的配置、启动？

**Comment by my8100** [comment]
@devxiaosong 
Replied in #107.

**Comment by Jasonjk3** [comment]
可以在页面上动态添加/删除 scrapyd 节点吗

**Comment by my8100** [comment]
> 可以在页面上动态添加/删除 scrapyd 节点吗

Editing Scrapyd servers via GUI is not supported.
