### ISSUE TITLE
about timer task

### ISSUE THREAD

**Issue by CoderZHV** [my8100/scrapydweb#44]
![图片](https://user-images.githubusercontent.com/13792304/57192722-0bfd2e80-6f66-11e9-8f74-6facf2111b80.png)
![图片](https://user-images.githubusercontent.com/13792304/57192762-8463ef80-6f66-11e9-844e-4de601cc4950.png)

I want the task to run at 18:00:00, but the task is running when i click [add task&fire right now] !  How can i do ? thanks sir

**Comment by my8100** [comment]
1. Select 'Add Task' from the 'Action' drop-down
2. Type '18' in the 'hour (*)' input field so that the task would be triggered at 18:00:00 every day

**Comment by CoderZHV** [comment]
thanks sir
