### ISSUE TITLE
为什么我的定时任务没有执行[BUG]

### ISSUE THREAD

**Issue by Dana168** [my8100/scrapydweb#45]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**
Add logs of ScrapydWeb and Scrapyd (optional) when reproducing the bug. (Run ScrapydWeb with argument '--verbose' if its version >= 1.0.0)

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Win 10, macOS 10.14, Ubuntu 18, centOS 7.6, Debian 9.6 or Fedora 29]
 - Python: [e.g. 2.7, 3.6 or 3.7]
 - ScrapydWeb: [e.g. 0.9.9 or 1.0.0]
 - Scrapyd amount [e.g. 1 or 5] 
 - Related settings [e.g. 'ENABLE_CACHE = True']
 - Browser [e.g. Chrome 71, Firefox 64 or Safari 12]

**Additional context**

**Comment by my8100** [comment]
Please learn how to new an issue first, see #30.
