### ISSUE TITLE
Why not support Timer tasks on specified time

### ISSUE THREAD

**Issue by EchoShoot** [my8100/scrapydweb#46]
比如: 工作日期间(周一到周五), 每天上午8:30 启动一次, 每天晚上5:00 启动一次.
For example: During the working day (Monday to Friday), start every day at 8:30 am, start every day at 5:00 pm.

至少我去过的几家爬虫公司的确有这样的需求.
At least some of the WebCrawl companies which I have been to ,it's truly have such a demand.

**Comment by my8100** [comment]
Does the config below work for you?
- day_of_week: Monday-Friday
- hour: 8,17
- minute: 0

**Comment by EchoShoot** [comment]
嘿朋友! 你的方案能用, 看来是我当时理解存在偏差. 不过我相信我不是唯一误解的人, 我有一个不错的建议:
参考GTD软件Things3的重复任务来设计:
Hey friends! Your plan can be used, it seems that I understood the deviation at the time. But I believe that I am not the only misunderstood person, I have a good suggestion: Refer to the repeated tasks of the GTD software Things3 to design:

---

重复条件: \ Repeat conditions
* 完成后 \ After completion
    * n (分钟/小时/天/周/月) 后执行  \  n (minutes/hours/days/weeks/months)
    * 结束条件 (从不/截止日期/n次后) \ Execution* End conditions (never/dead date/n times)
* 定期 \ Regular
    * 每(天/周/月) (12:00, 13:30) 执行 \ per (day/week/month) (12:00 , 13:30)
    * 结束条件 (从不/截止日期/n次后) \ Execution* End condition (never/dead date/n times)

---

我相信这样设计能够应对更多的场景, 能够更加便于理解与使用. 
I believe that this design can handle more scenarios and can be more easily understood and used.

---

your guy: BiarFordlander

**Comment by my8100** [comment]
Thanks for your suggestion.

1. The *Timer Tasks* feature is implemented based on [*APScheduler*](https://apscheduler.readthedocs.io/en/latest/).
2. Whether a scraping job is finished or not **is unknown to** *APScheduler*, see #30.
3. The `max_runs` option is dropped in [APScheduler v3.0.0](https://apscheduler.readthedocs.io/en/latest/versionhistory.html?highlight=max_runs#id17), so currently you **cannot specify** how many times a task should be executed.
4. Setting `*/n` means firing every `n` values, starting from the minimum, see [the docs of APScheduler](https://apscheduler.readthedocs.io/en/latest/modules/triggers/cron.html#expression-types).
5. Both `start_date` and `end_date` are **available and optional** when adding a task.

Also, check out the links in the HELP section of the *Timer Tasks* page to get more info.
