### ISSUE TITLE
scrapyd always stoped

### ISSUE THREAD

**Issue by CoderZHV** [my8100/scrapydweb#47]
Hello sir.
I have two server. scrapydweb and scrapyd is running on 166, 110 only have scrapyd. 
but. at 110, the scrapyd always stop after run some times. why ? thinks sir
.
![image](https://user-images.githubusercontent.com/13792304/57841481-315b2980-77fd-11e9-9a1d-c95c3eafce3b.png)

**Comment by my8100** [comment]
Please turn to repo [Scrapyd](https://github.com/scrapy/scrapyd) for help.
