### ISSUE TITLE
由于目标计算机积极拒绝

### ISSUE THREAD

**Issue by guapier** [my8100/scrapydweb#5]
win10 ,anaconda python3.6 { "auth": null, "message": "HTTPConnectionPool(host='127.0.0.1', port=6800): Max retries exceeded with url: /daemonstatus.json (Caused by NewConnectionError(': Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))", "status": "error", "status_code": -1, "url": "http://127.0.0.1:6800/daemonstatus.json" }

**Comment by my8100** [comment]
Debug by opening the below url in your browser:
http://127.0.0.1:6800/daemonstatus.json

**Comment by guapier** [comment]
@my8100  I got it why i failed, because you should start scrapyd first before you start scrapydweb
