### ISSUE TITLE
when I click [Timer Tasks], I will wait 5 minutes ！

### ISSUE THREAD

**Issue by CoderZHV** [my8100/scrapydweb#50]
I have 6 tasks in timer tasks list,  when i click [Timer Tasks], I will take 5 minutes to get the result, so slow ！ why ?  only [Timer Tasks] !

![image](https://user-images.githubusercontent.com/13792304/58602090-189f4900-82be-11e9-876f-7d3417d10b29.png)

**Comment by my8100** [comment]
How often are the tasks being executed? On every N seconds?

**Comment by CoderZHV** [comment]
5 seconds

**Comment by my8100** [comment]
A way to work around is increasing the execution interval of the tasks, like every minute. 
See https://github.com/my8100/scrapydweb/issues/42#issuecomment-487838360
