### ISSUE TITLE
怎样暂停或停止，我删除了任务 ，还是照样运行

### ISSUE THREAD

**Issue by ServletJunior** [my8100/scrapydweb#51]

**Comment by my8100** [comment]
Are there any pending jobs in the *jobs* page after you deleted the timer task?

**Comment by ServletJunior** [comment]
> Are there any pending jobs in the _jobs_ page after you deleted the timer task?

不管我有没有删除任务，都是显示成这样
![微信截图_20190530141429](https://user-images.githubusercontent.com/16482652/58612190-4bf4ce80-82e4-11e9-9332-1ab95bc01af9.png)

**Comment by my8100** [comment]
See step 4 in https://github.com/my8100/files/blob/master/scrapyd-basic-auth/README.md#try-it-out

**Comment by ServletJunior** [comment]
> See step 4 in https://github.com/my8100/files/blob/master/scrapyd-basic-auth/README.md#try-it-out

我现在已经更新job页面了，在任务 点击stop还是会一直运行
![111](https://user-images.githubusercontent.com/16482652/58613984-bb20f180-82e9-11e9-8706-2a07b73c230f.png)

**Comment by my8100** [comment]
But there are no running jobs in your screenshot.

**Comment by ServletJunior** [comment]
> See step 4 in https://github.com/my8100/files/blob/master/scrapyd-basic-auth/README.md#try-it-out

我又新建一个任务，在job页面stop或者forceStop的时候都会报这个错误
![111 - 副本](https://user-images.githubusercontent.com/16482652/58614374-c0cb0700-82ea-11e9-9956-e275ffe17cd2.png)

**Comment by my8100** [comment]
See https://github.com/my8100/scrapydweb/issues/7#issuecomment-485254942

**Comment by ServletJunior** [comment]
> See [#7 (comment)](https://github.com/my8100/scrapydweb/issues/7#issuecomment-485254942)

我看了一下logs，没有错误，我用了无头浏览器来爬，不知道是不是这个原因

**Comment by my8100** [comment]
It seems so.
https://github.com/my8100/scrapydweb/issues/7#issuecomment-485246846
https://github.com/my8100/scrapydweb/issues/7#issuecomment-485247391

**Comment by ServletJunior** [comment]
> It seems so.
> [#7 (comment)](https://github.com/my8100/scrapydweb/issues/7#issuecomment-485246846)
> [#7 (comment)](https://github.com/my8100/scrapydweb/issues/7#issuecomment-485247391)

谢谢，在cmd运行了scrapydweb -v ，可以正常停止了，最后一个问题，就是items页面显示404
<img width="722" alt="111 - 副本" src="https://user-images.githubusercontent.com/16482652/58634405-cdb51e00-831d-11e9-9c66-2c8d9833286e.png">

**Comment by my8100** [comment]
Actually, adding the argument ‘-v’ only change the logging level of scrapydweb. 
As for the *items* page, see https://scrapyd.readthedocs.io/en/stable/config.html#items-dir

BTW, try to communicate in English on GitHub.

**Comment by ServletJunior** [comment]
> Actually, adding the argument ‘-v’ only changes the logging level of scrapydweb.
> As for the _items_ page, see https://scrapyd.readthedocs.io/en/stable/config.html#items-dir
> 
> BTW, try to communicate in English on GitHub.

ok! thx! Is FEED_URI written in settings. py of the scrapy project?
