### ISSUE TITLE
Is it possible to run a python script?

### ISSUE THREAD

**Issue by aysark** [my8100/scrapydweb#52]
Not a bug, just a question.  I want to run a python script (as a job), it seems it should be possible to do.  You can do this in scrapinghub.

Thanks for the great package!

**Comment by my8100** [comment]
I cannot find the entrance to run a python script on Scrapy Cloud.
Could you post some screenshots?

**Comment by aysark** [comment]
Check: https://blog.scrapinghub.com/2016/09/28/how-to-run-python-scripts-in-scrapy-cloud

**Comment by my8100** [comment]
ScrapydWeb can't support this feature as [Scrapyd](https://scrapyd.readthedocs.io/en/latest/api.html) doesn't provide the API.
The [_Email notice_](https://github.com/my8100/files/blob/master/scrapydweb/README.md#email-notice) feature of scrapydweb would do a better job
if you only want to monitor your spiders.
