### ISSUE TITLE
[BUG] How to remove Finished Job spider named "Spider" on "Project"

### ISSUE THREAD

**Issue by sulthonzh** [my8100/scrapydweb#53]
**Describe the bug**
Got this error 
"Fail to persist jobs in database: time data 'Start' does not match format '%Y-%m-%d %H:%M:%S'"
when click "Database" because on Finished Jobs have spider list completed named "Spider" on "Project" 

**To Reproduce**
1. Go to 'http://<host>:<port>/<project_id>/jobs'
2. Click on 'Database'

**Screenshots**
![image](https://user-images.githubusercontent.com/4921059/59597786-dcc10c00-9124-11e9-9295-0518cc37fcfa.png)

**Comment by my8100** [comment]
Are you using Scrapyd installed via git?
If so, `pip install -U git+https://github.com/my8100/scrapydweb.git`

**Comment by sulthonzh** [comment]
hooo, i see,
yeah right, i have installed scrapyd via git like this ```pip install git+https://github.com/scrapy/scrapyd.git```

**Comment by my8100** [comment]
Is the problem solved?

**Comment by sulthonzh** [comment]
![image](https://user-images.githubusercontent.com/4921059/59647907-44b83680-91a7-11e9-9ae3-283eac779e6a.png)
yeah I think this is solved, 
thanks @my8100
