### ISSUE TITLE
The log is so big

### ISSUE THREAD

**Issue by xunqirui** [my8100/scrapydweb#54]
I runed my spider by using scrapydweb,after a few days latter,I found my spider's logfile was so big,and it took me a lot of time to open it.
can you give me some advice?
thank you :)

**Comment by my8100** [comment]
1. Visit the corresponding [Stats page](https://github.com/my8100/files/blob/master/scrapydweb/README.md#log-analysis--visualization) in scrapydweb, then switch to the *Log categorization* tab,
and find out the amount of different level of logs.
2. You may also need to set up  `LOG_LEVEL` of your spider to control the logging level, see [docs](https://docs.scrapy.org/en/latest/topics/settings.html#log-level).

BTW, there's no need to open the original log of the spider as scrapydweb provides the Stats page.

**Comment by xunqirui** [comment]
I changed my LOG_LEVEL,and the log has been decreased a lot,then I will try to use LogParser,I find it is very useful.
Thank you!!

**Comment by Digenis** [comment]
Also see logrotation through the built-in logging module:
https://github.com/scrapy/scrapy/issues/3235

logrotate(8) is also an option https://github.com/scrapy/scrapy/issues/3628
but make sure you test it thoroughly with scrapy.
It gave me issues with corruption of the first bytes of every new scrapyd log file
(which is written by twisted.python.log, not the built-in logging module).

**Comment by xunqirui** [comment]
@my8100 
I changed my LOG_LEVEL,and the log has been decreased a lot,then I will try to use LogParser,I find it is very useful.
Thank you!!

**Comment by xunqirui** [comment]
@Digenis when i found the log file was so big,i also wanted to use logrotation,but i didn't find a better way.your suggestions also help me a lot.
thank you!

**Comment by my8100** [comment]
@xunqirui 
But logrotation would break LogParser.

**Comment by xunqirui** [comment]
@my8100 The LogParser is very useful,If the logrotation would break LogParser,I will not use the logrotation.I changed the LOG_LEVEL,the log has been decreased a lot.It has met my needs.
thank you for reminding me!!!!

**Comment by my8100** [comment]
@xunqirui 
Don‘t forget to add a space after the punctuation mark.
Add a new line if needed.
: )

**Comment by xunqirui** [comment]
@my8100 
Haha
I haven't chatted with others in English for a long time.
I will re-edit it.
: )
