### ISSUE TITLE
Default value for "Check Cmd"

### ISSUE THREAD

**Issue by botzill** [my8100/scrapydweb#56]
Would be nice to fill the "Check CMD" options when running a spider.

**Comment by my8100** [comment]
The *Check CMD* button is used for checking your inputs and selections
before *Run Spider*.

**Comment by botzill** [comment]
I see, but most of the time I just check it because I have to :) to run the spider, maybe optional?

**Comment by my8100** [comment]
No, the two-steps operation is compulsory behind the scene.

**Comment by botzill** [comment]
OK, thx @my8100
