### ISSUE TITLE
About timezone of Timer Tasks

### ISSUE THREAD

**Issue by JQ-K** [my8100/scrapydweb#59]
我在 timer tasks 设置了每天8点启动 ，19点关闭

在 settings & arguments -》 DOWNLOAD_DELAY -》additional  添加了 -d setting=CLOSESPIDER_TIMEOUT=39600

但是 设置之后，发现在 19点的时候爬虫还在运行，并且启动时间是零点，与预期相差8个小时，所以我怀疑是不是跟时区有关系，系统默认的是零时区时间

![image](https://user-images.githubusercontent.com/14874834/60322899-39d58100-99b3-11e9-8a06-8f5c294493e3.png)

![image](https://user-images.githubusercontent.com/14874834/60322980-6db0a680-99b3-11e9-86ff-4dbc45bd0a7d.png)

**Comment by my8100** [comment]
1. Run Spider -> timer task -> show more timer settings -> clean the content in timezone -> share your screenshot like this:
![image](https://user-images.githubusercontent.com/37427675/60324030-3c85a580-99b6-11e9-9925-c89f6ca28a46.png)
2. Timer Tasks -> click on task # 1 -> share your screenshot like this:
![image](https://user-images.githubusercontent.com/37427675/60324127-7d7dba00-99b6-11e9-8120-95f5f630246d.png)

**Comment by JQ-K** [comment]
thx,

**Comment by my8100** [comment]
Where are the pics?
