### ISSUE TITLE
'jinja2.runtime.LoopContext object' has no attribute 'changed'

### ISSUE THREAD

**Issue by sanpi0205** [my8100/scrapydweb#6]
the web interface encounter a 500 error,  the log show the following:

 {% if SCRAPYD_SERVERS_GROUPS[loop.index-1] and loop.changed(SCRAPYD_SERVERS_GROUPS[loop.index-1]) %}
jinja2.exceptions.UndefinedError: 'jinja2.runtime.LoopContext object' has no attribute 'changed'

**Comment by my8100** [comment]
@sanpi0205 Could you tell me what happened?
