### ISSUE TITLE
How to run ScrapydWeb in the background

### ISSUE THREAD

**Issue by ChWasiUllah** [my8100/scrapydweb#73]
**Scrapydweb is automatically turned off after some time**
I started scrapydweb as daemon service by command`scrapydweb &`.  It works fine for some time.  But later it is shut down automatically.  I also found 1 warning when I start scrapydweb

>    WARNING: This is a development server. Do not use it in a production deployment.
>    Use a production WSGI server 
> 

**Environment:**
 - OS: Ubuntu 18
 - Python: 2.7
 - ScrapydWeb: 1.2.0
 - Scrapyd amount:  1

**Comment by my8100** [comment]
1. Here is how I run ScrapydWeb in the background.
If it's still killed frequently, you should check the free RAM of your server.
```
nohup scrapydweb > scrapydweb.log 2>&1 &
```
2. As for the warning log, see issue #17.

**Comment by crud-boy** [comment]
```
apt install nodejs
apt install npm
npm i --g pm2
echo "scrapyd" >> scrapyd.sh
pm2 start scrapyd.sh         
pm2 ls
pm2 --help
```

PM2 considers app as a JS file, so it needs to be started through the. sh file
Don't use `nohup`, because before you use nohup, if you don't start `screen`, you will close the process after the SSH session ends, and it's inconvenient to manage the process.

**Comment by my8100** [comment]
nohup works for me:
```
nohup scrapydweb > scrapydweb.log 2>&1 &
```

**Comment by NgeKaworu** [comment]
it's works for me

```
#/usr/lib/systemd/system/scrapydwebd.service
[Unit]
Description=scrapydweb
After=network.target

[Service]
ExecStart=/usr/bin/bash /home/scrapydweb/scrapydwebd.sh

[Install]
WantedBy=multi-user.target
```

```bash
#/home/scrapydweb/scrapydwebd.sh
cd /home/scrapydweb/ && /root/workspaces/scrapy/bin/scrapydweb
```

```bash
systemctl start scrapydwebd
```

**Comment by my8100** [comment]
@NgeKaworu 
Thank your for the sharing.

**Comment by kstar0101** [comment]
> it's works for me
> 
> ```
> #/usr/lib/systemd/system/scrapydwebd.service
> [Unit]
> Description=scrapydweb
> After=network.target
> 
> [Service]
> ExecStart=/usr/bin/bash /home/scrapydweb/scrapydwebd.sh
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> ```shell
> #/home/scrapydweb/scrapydwebd.sh
> cd /home/scrapydweb/ && /root/workspaces/scrapy/bin/scrapydweb
> ```
> 
> ```shell
> systemctl start scrapydwebd
> ```

I use [WorkingDirectory] option instead scrapydwebd.sh.
ex:
```
WorkingDirectory=/home/scrapydweb/
ExecStart=/root/workspaces/scrapy/bin/scrapydweb
```
