### ISSUE TITLE
Is it possible to schedule one scrapy spider every 4 hours?

### ISSUE THREAD

**Issue by heilwood** [my8100/scrapydweb#86]
Is it possible to schedule one scrapy spider execution every 4 hour with one timer task?

**Comment by my8100** [comment]
Clear the default value in the input box to get the help info.

![image](https://user-images.githubusercontent.com/37427675/63236576-d8be8100-c270-11e9-86bb-6e0a14910602.png)

**Comment by heilwood** [comment]
Thank you!
