### ISSUE TITLE
[BUG] Spider close status cannot show correctly

### ISSUE THREAD

**Issue by lx1054331851** [my8100/scrapydweb#89]
If I click the stop button to suspend a spider, although the spider have been suspended on the server, but the stop button does not change to "start", it always show "stop", as below pictures show:
![image](https://user-images.githubusercontent.com/12423206/63751652-5c681580-c8e2-11e9-9600-53aba9bc53f3.png)
![image](https://user-images.githubusercontent.com/12423206/63751704-76a1f380-c8e2-11e9-8787-672681199965.png)

**Comment by my8100** [comment]
Check if the job is still in the running state in http://127.0.0.1/jobs

**Comment by lx1054331851** [comment]
I found some times the status can correctly show after I clicked the stop button twice.

**Comment by my8100** [comment]
Actually, the Jobs page of ScrapydWeb is dynamically generated based on the original Jobs page of Scrapyd. 
Always check the Scrapyd page to see whether a job is running or finished.
