### ISSUE TITLE
[BUG]这玩意有人在生产环境用过吗？BUG漫天飞啊不忍直视，最基础的功能都完全都不能用

### ISSUE THREAD

**Issue by Irvinghua** [my8100/scrapydweb#91]
![image](https://user-images.githubusercontent.com/2010962/65042515-91b8ce00-d98b-11e9-97f5-cce07ed14b57.png)

1.建了3个定时任务，删了一个，刷新页面，右上角图标一直显示3.
而且不知道这3个图标是显示啥信息，好歹给个tooltip提示呀

2第一次.建了一个测试定时任务，确实能触发立即执行。删了重建一个真正的任务。点击fire不执行，或者把定时任务设置到当前时间几分钟后，时间到了不执行。反复删了建，建了删，后面没有一次执行过

3.删了job，该job 的历史日志依然显示在log菜单里。log估计是太大了加载不出来看不了，默认搞个tail -500 logfile也行啊

**Comment by my8100** [comment]
`pip uninstall scrapydweb`
