### ISSUE TITLE
[BUG] 启动时间不对

### ISSUE THREAD

**Issue by crud-boy** [my8100/scrapydweb#95]
任务总是自动启动，而且是每个小时后启动一次
Next run time: 2019-10-07 21:00:05+08:00

trigger 支持cron吗？ 

date和interval呢

add task & pause it 这个不是interval吗，任务没启动啊
add task & fire right now 这个好像date，但是每个小时都会自动启动一次
add task 应该是cron吧

**Comment by crud-boy** [comment]
emmmm， demo版本有输入框提示，自己安装的就没有问号提示

**Comment by my8100** [comment]
To get the latest version from git, see https://github.com/my8100/scrapydweb/blob/master/README.md

**Comment by crud-boy** [comment]
git拉下来的，点开timer tasks后，显示的action，一直是add task & fire right now

**Comment by my8100** [comment]
Can you show me the screenshot?

**Comment by crud-boy** [comment]
![image](https://user-images.githubusercontent.com/46029824/66312241-df997400-e942-11e9-8d6c-b8b2cc48f3ca.png)
![image](https://user-images.githubusercontent.com/46029824/66312314-06f04100-e943-11e9-8101-fcd8ef5b02e1.png)

**Comment by my8100** [comment]
I don’t see anything wrong.

**Comment by crud-boy** [comment]
默认的*  又不能删掉，自动每个小时都启动

**Comment by my8100** [comment]
What’s your target?

**Comment by my8100** [comment]
What’s the meaning of“每天启动一次重置任务”?

**Comment by crud-boy** [comment]
Start every day

**Comment by my8100** [comment]
In which hour of every day?

**Comment by crud-boy** [comment]
hour: 6

**Comment by my8100** [comment]
Why not just set the hour option to 6?

**Comment by crud-boy** [comment]
06:00:01 AM

**Comment by my8100** [comment]
Simply set the minute and second option accordingly...
