### ISSUE TITLE
[BUG] 日志文件丢失

### ISSUE THREAD

**Issue by crud-boy** [my8100/scrapydweb#97]
'''
    Request to http://127.0.0.1:6800/logs/bf_1/bf/task_2_2019-10-08T05_30_00.json got code 404, wait until LogParser parses the log.
    Fail to request logfile from http://127.0.0.1:6800/logs/bf_1/bf/task_2_2019-10-08T05_30_00 with extensions ['.log', '.log.gz', '.txt']

Oops! Something went wrong.
'''

已经配置logparser了，但是日志还是丢失，只有最新的几个job的日志正常

**Comment by my8100** [comment]
You need to increase the value of jobs_to_keep in the config file of Scrapyd, see https://scrapyd.readthedocs.io/en/stable/config.html#jobs_to_keep
