### ISSUE TITLE
scrapydweb creates zombie processes

### ISSUE THREAD

**Issue by aysark** [my8100/scrapydweb#99]
**Describe the bug**
 scrapydweb creates zombie processes

**To Reproduce**
Vanilla installation and ran for months on server...

**Expected behavior**
No zombies

**Screenshots**
![image](https://user-images.githubusercontent.com/654356/67165953-d85d6780-f33f-11e9-977d-d12e3a70a98a.png)

**Comment by my8100** [comment]
Anything wrong in your screenshot?
